global:
  scrape_interval:     1s

scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]
  - job_name: 'Backend_1'
    static_configs:
      - targets: ['84.201.165.50']

  - job_name: 'Backend_2'
    static_configs:
      - targets: ['84.201.164.41']

  - job_name: 'Backend_3'
    static_configs:
      - targets: [ '84.201.166.194']